-- +migrate Up
ALTER TABLE runs DROP COLUMN IF EXISTS created_at;
ALTER TABLE runs ALTER COLUMN cost TYPE DOUBLE PRECISION;
-- +migrate Down
ALTER TABLE runs ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
ALTER TABLE runs ALTER COLUMN cost TYPE NUMERIC(12,6);
